# Generated by Django 4.0.4 on 2022-05-25 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo_usuario', models.CharField(max_length=50)),
                ('descripcion_tipo_usuario', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_id_usuario', models.IntegerField()),
                ('rut_usuario', models.CharField(max_length=100)),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('apellido_usuario', models.CharField(max_length=100)),
                ('correo_usuario', models.EmailField(max_length=100)),
                ('contrasena_usuario', models.CharField(max_length=100)),
                ('tipo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.tipo_usuario')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Todos los usuarios',
                'unique_together': {('rut_usuario',)},
            },
        ),
    ]
