# Generated by Django 4.0.4 on 2022-05-25 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_tipo_usuario_nombre_tipo_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='id',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='code_id_usuario',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.ForeignKey(choices=[('0', 'GERENTE'), ('1', 'VENDEDOR'), ('2', 'BODEGUERO'), ('3', 'CONTADOR')], max_length=1, on_delete=django.db.models.deletion.CASCADE, to='store.tipo_usuario'),
        ),
    ]
