# Generated by Django 4.0.4 on 2022-05-25 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_usuario_rut_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_usuario',
            name='nombre_tipo_usuario',
            field=models.CharField(choices=[('0', 'GERENTE'), ('1', 'VENDEDOR'), ('2', 'BODEGUERO'), ('3', 'CONTADOR')], max_length=1, verbose_name='Tipo de Usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.tipo_usuario'),
        ),
    ]
