# Generated by Django 4.0.4 on 2022-05-25 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_tipo_usuario_nombre_tipo_usuario_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipo_usuario',
            options={'verbose_name': 'Tipo de Usuario', 'verbose_name_plural': 'Tipos de Usuarios'},
        ),
        migrations.AlterUniqueTogether(
            name='tipo_usuario',
            unique_together={('nombre_tipo_usuario', 'descripcion_tipo_usuario')},
        ),
    ]
