# Generated by Django 4.0.4 on 2022-05-25 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_tipo_usuario_nombre_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_usuario',
            name='descripcion_tipo_usuario',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellido_usuario',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contrasena_usuario',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo_usuario',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre_usuario',
            field=models.CharField(max_length=50),
        ),
    ]
